defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-imagenet100-linear-512"
backbone:
  name: "resnet18"
pretrain_method: "simclr"
data:
  dataset: imagenet100
  train_path: "data/imagenet100/train"
  val_path: "data/imagenet100/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 128
  lr: 1.0
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [15,20]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
method_kwargs:
  proj_hidden_dim: 16384
  proj_output_dim: 2048

# overwrite PL stuff
max_epochs: 25
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
finetune: False
selected_dims: 256


